### ISSUE TITLE
Error Kamerka-GUI

### ISSUE THREAD

**Issue by Alex138** [woj-ciech/Kamerka-GUI#12]
![Screenshot_1](https://user-images.githubusercontent.com/33782329/76162693-24883780-617b-11ea-82ae-83eb0da68387.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/33782329/76162694-26ea9180-617b-11ea-8c11-0b92db9b64a1.jpg)

For what reason Google map may not be displayed?

**Comment by Alex138** [comment]
> ![Screenshot_1](https://user-images.githubusercontent.com/33782329/76162693-24883780-617b-11ea-82ae-83eb0da68387.jpg)
> ![Screenshot_2](https://user-images.githubusercontent.com/33782329/76162694-26ea9180-617b-11ea-8c11-0b92db9b64a1.jpg)
> 
> For what reason Google map may not be displayed?

**Comment by abarracu** [comment]
You had my same problem, the problem is the asynchronous call of the javascript. Try to remove "defer" on line number 115 of the file "map.html".
