### ISSUE TITLE
Issue with celery

### ISSUE THREAD

**Issue by ceyricc** [woj-ciech/Kamerka-GUI#26]
Hello,

when trying to run celery worker, I get this error:

**_You are using `-A` as an option of the worker sub-command:
celery worker -A celeryapp <...>

The support for this usage was removed in Celery 5.0. Instead you should use `-A` as a global option:
celery -A celeryapp worker <...>_**

I don't know how to fix this. I'm running **_celery worker -A kamerka --loglevel=info_** as stated in the Kamerka readme.

**Comment by ceyricc** [comment]
So i fixed this by installing a lower version of celery, but now I get this error: 

Unable to load celery application.
The module kamerka was not found.

**Comment by woj-ciech** [comment]
For newest version of celery please run ```celery --app kamerka worker```
