### ISSUE TITLE
Map won't load, JS console

### ISSUE THREAD

**Issue by 8824348d** [woj-ciech/Kamerka-GUI#27]
Hi, I've been trying to use the Google Maps feature without success.
![Screenshot_2021-05-28 Map - ꓘamerka](https://user-images.githubusercontent.com/84974850/119988058-61358e00-bfce-11eb-9db6-41684a6804b7.png)

**Comment by woj-ciech** [comment]
What console says? I guess you haven't created and pasted you API key properly.
