### ISSUE TITLE
I fixed some issues with oauth for twitter in keys.json and tasks.py and README.md with insights about google maps.

### ISSUE THREAD

**Issue by ghost** [woj-ciech/Kamerka-GUI#34]
I noticed there's no oauth key for twitter in keys.json, would this be needed or no?

**Comment by g33kz4su** [comment]
![image](https://user-images.githubusercontent.com/76766272/125637409-44fbf346-07a7-4ee7-b0f9-2e0612c820c5.png)
oh, nevermind, seems to be working just fine, any tips to run this?

**Comment by g33kz4su** [comment]
wait i found the oauth error, 
```python
Traceback (most recent call last):
  File "/home/mrgfy/.local/lib/python3.9/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/xxxxx/.local/lib/python3.9/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/Kamerka-GUI/kamerka/tasks.py", line 787, in twitter_nearby_task
    twitter = Twitter(auth=OAuth(TWITTER_ACCESS_TOKEN,
NameError: name 'Twitter' is not defined
```

**Comment by g33kz4su** [comment]
you guys should add the Oath to keys.json, i'll try to and if successful i'll post it.

**Comment by g33kz4su** [comment]
i think i fixed it.
![image](https://user-images.githubusercontent.com/76766272/125674324-23e22056-cc86-4636-aa66-80e563656f5c.png)
![image](https://user-images.githubusercontent.com/76766272/125674484-0c99c0ec-1e98-4d27-a504-16d74df56066.png)

**Comment by g33kz4su** [comment]
oh, i forgot to mention, google maps is working without needing an api key.

**Comment by g33kz4su** [comment]
In the README.md on the celery part, is also wrong.
original code ``` celery worker -A kamerka --loglevel=info ```
correct code ``` celery worker --app=kamerka -l INFO ``` l = lower case L (in case anyone was confused)

**Comment by g33kz4su** [comment]
i just realized the last line in the second code block picture is missing the word SECRET and miss spelled TOKEN.
 
![image](https://user-images.githubusercontent.com/76766272/125728598-4326ecfb-12b3-4f00-ba6a-4629a10ef851.png)
