### ISSUE TITLE
I cant search with Internet of Things. Can you helps me pls.

### ISSUE THREAD

**Issue by bangpk** [woj-ciech/Kamerka-GUI#44]
![problem](https://user-images.githubusercontent.com/41537634/180405572-c006a782-7477-40b9-bbea-d601826bf593.png)
![ảnh](https://user-images.githubusercontent.com/41537634/180406115-83085395-b9a3-4ba1-a4d3-781c8ed56d51.png)

**Comment by ovetimepog** [comment]
also getting this error, don't know what the error is

**Comment by ovetimepog** [comment]
it has something to do with the 

country == "XX" line, cause country is defined as None in the function, so it's trying to get a string from it, and cant. 
I have no clue how to fix this but I'm hoping you can find something

**Comment by ovetimepog** [comment]
Fixed this in my pull request :)

**Comment by bangpk** [comment]
Thanks so much :)
