### ISSUE TITLE
Country filter not applied

### ISSUE THREAD

**Issue by Evilcry** [woj-ciech/Kamerka-GUI#48]
It seems that from the latest commit (`a00d571f156882ade9e83eef7d54197368ef4878`) the filter per country is no longer applied, as a result the search contains IPs/Entries from all over the world eventhough the country filter has been selected.

**Comment by woj-ciech** [comment]
Fixed in https://github.com/woj-ciech/Kamerka-GUI/commit/07fc349b1248cdb3d07d3f04c6d2357675cb35b2 
Thank you :)

**Comment by Evilcry** [comment]
Awesome! many thanks :)

**Comment by overtimepog** [comment]
Nice :)
