### ISSUE TITLE
Celery error in fresh installation

### ISSUE THREAD

**Issue by lonione** [woj-ciech/Kamerka-GUI#49]
Hi,
trying to deploy Kamerka in a new instance of Kali 2022.1

Everything installs correctly, requirements are met, redis runs, celery runs, Kamerka server runs. Keys are present in keys.json
Dashboard appears on localhost:8000 but when any search is performed, no results are shown, and the following error is loggen in the celery worker windows:

[2023-01-12 07:31:08,141: WARNING/ForkPoolWorker-4] port:18245,18246 product:"general electric"
[2023-01-12 07:31:11,218: WARNING/ForkPoolWorker-4] fail1, sleeping...
[2023-01-12 07:31:14,296: WARNING/ForkPoolWorker-4] fail1, sleeping...
[2023-01-12 07:31:17,357: WARNING/ForkPoolWorker-4] fail1, sleeping...
etc.

How best to troubleshoot & fix this?

**Comment by woj-ciech** [comment]
Hey,

This exception occurs when there is a connection error to Shodan https://github.com/woj-ciech/Kamerka-GUI/blob/fcfe888e1c53d396da242610f13af21ae733cae7/kamerka/tasks.py#L629

Check your connection and API key, you can do it on your own with
```
api = Shodan(SHODAN_API_KEY)
results = api.search("geo:" + coordinates + ",20 " + query, page)
```

**Comment by JackG55** [comment]
How about check a Google Map API key???

**Comment by lonione** [comment]
You were correct, it was a connection issue (caused by using a SSL proxy.)
Thank You!
