### ISSUE TITLE
URL pattern Error

### ISSUE THREAD

**Issue by ronb65** [woj-ciech/Kamerka-GUI#6]
While typing the python3 manage.py makemigrations command, getting this error:
(2_0.W001) Your URL pattern '^celery-progress/' has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path().

Any idea why?
Thanks

**Comment by woj-ciech** [comment]
That's legacy from Django 2.0 but it does not impact execution, doesn't it?

**Comment by ronb65** [comment]
Well, the server works, but when I try to search something on the IOT tab it's immediately sending me back to the ICS tab. Same for searching in the ICS tab. So I thought that's the problem.. what could be the problem?
btw, when I enter redis-server on my window explorer nothing happens.

**Comment by woj-ciech** [comment]
I just cloned the repo on my Ubuntu and it works like expected.
What do you mean nothing happens? You should install Redis database first by executing "sudo apt install redis-server" and then execute it before celery.

**Comment by ronb65** [comment]
Maybe it's because I'm using Windows?
Haven't seen that I need to install the Redis DB anywhere haha

**Comment by woj-ciech** [comment]
Might be, I did not test it on Windows.
I will add detailed installation guide then

**Comment by ronb65** [comment]
Thank you!
