### ISSUE TITLE
is there a solution

### ISSUE THREAD

**Issue by prince911** [woj-ciech/Kamerka-GUI#7]
OperationalError at /

Error 111 connecting to localhost:6379. Connection refused.

Request Method: 	POST
Request URL: 	http://127.0.0.1:8000/
Django Version: 	2.2.7
Exception Type: 	OperationalError
Exception Value: 	

Error 111 connecting to localhost:6379. Connection refused.

Exception Location: 	/usr/local/lib/python3.7/dist-packages/redis/connection.py in connect, line 544
Python Executable: 	/usr/bin/python3
Python Version: 	3.7.5
Python Path: 	

['/root/Kamerka-GUI',
 '/root/Kamerka-GUI',
 '/usr/lib/python37.zip',
 '/usr/lib/python3.7',
 '/usr/lib/python3.7/lib-dynload',
 '/usr/local/lib/python3.7/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/lib/python3.7/dist-packages']

Server time: 	Fri, 3 Jan 2020 18:35:34 +0000

**Comment by prince911** [comment]
Kamerka-GUI work or not

**Comment by woj-ciech** [comment]
Obviously, there is something wrong with your Redis database. Make sure it's running. From error message you can know that it can't connect to port 6379
