### ISSUE TITLE
No results and map will not load

### ISSUE THREAD

**Issue by coachacg** [woj-ciech/Kamerka-GUI#8]
Hello,

The dashboard is loading fine and I see requests hitting Shodan. However, I have added Google API, BinaryEdge API and WhoIsXML API but no usage is being displayed in my Google account as well as the others. I have performed several searches with no results. The Map section in the dashboard stays in a loading state. What can be missing? BTW, these are all free accounts, in case it matters. Thank you for your help.

**Comment by woj-ciech** [comment]
Hi,
The most important part here is Shodan, it has to be paid version to use API with filters. Shodan gives no results so nothing will be loaded.

**Comment by shepardac** [comment]
So I have shodan credits and the app is not acknowledging? In addition is there any way to use this without pulling from a paid shodan account?

**Comment by woj-ciech** [comment]
Unfortunately no, it's based on the filters so Shodan paid plan is necessary. But don't worry, in next couple day I will add possibility to upload your scan from NMAP.
