### ISSUE TITLE
Own Server

### ISSUE THREAD

**Issue by dnkls** [woj-ciech/Kamerka-GUI#9]
Where i can change localhost ip ( http://127.0.0.1:8000/)  to my  VPS ip ? I install Kamrka to my own server but don't understand how connect  (

**Comment by Affector** [comment]
You can set a Reverse Proxy in your webserver. This is my setup in Nginx:

```
     	location / {
         	proxy_set_header   X-Forwarded-For $remote_addr;
         	proxy_pass         http://localhost:8000;
     	}
```
If you use Apache or some other webserver, use Google. Good Luck!
